version: '3'
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      # - mqtt_data:/mosquitto
      - C:\mosquitto\config:/mosquitto/config
      - C:\mosquitto\data:/mosquitto/data
      - C:\mosquitto\log:/mosquiitto/log

  nodered:
    build: ./nodered
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      # - nodered_data:/mqtt_data
      - nodered_data:/data
    depends_on:
      - mqtt

volumes:
  mqtt_data:
  nodered_data: